import turtle
turtle.circle(30)
turtle.penup()
turtle.goto(70,0)
turtle.pendown()
turtle.circle(30)
turtle.penup()
turtle.goto(35,-35)
turtle.pendown()
turtle.circle(30)
turtle.penup()
turtle.goto(-70,0)
turtle.pendown()
turtle.circle(30)
turtle.penup()
turtle.goto(-35,-35)
turtle.pendown()
turtle.circle(30)
